### ISSUE TITLE
Switch from GitLab to GitHub

### ISSUE THREAD

**Issue by cameronrutherford** [pnnl/ExaGO#1]
Before Initial Switch:
- [x] Clean up stale branches / issues (#37) 
- [x] Merge any remaining work in MRs
- [x] Issues moved from GitLab to GitHub (also move any stale PRs manually)
- [x] PNNL GitLab push mirror (#7)
- [x] PNNL GPU pipelines posting status (#7)
- [x] Ascent pipelines posting status (#7)

After Initial Switch:
- [x] Tag new release to signify switch, and update spack package with URL + version (Planned 1.6.0)
  - [x] Ensure tags are updated and all branches match
- [x] Update about section and logo in GitHub (@abhyshr took care of this)
- [x] Add Issue / Merge request template (#36)
- [x] Badges updated for pipelines / ExaGO logo update (#15)
  - [x] This includes the new GitHub actions, and pre-commit (maybe codecov one day) [![pre-commit](https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit)](https://github.com/pre-commit/pre-commit)
- [x] Crusher pipelines fixed and posting status. (#9)
- [x] GitHub Actions pipelines
  - [x] pre-commit instead of CMake based linting (#5)
  - [x] spack CI builds in GitHub actions for CPU only builds (#11 #15)

Follow up work:
- [x] Quarto Documentation + GitHub wiki integration (#32) 
- [x] Crusher CI status posting (#9) 
- [x] Add spack module pipelines to Ascent and Crusher (#10 #34) 
- [x] Submodules removed in favor of external packages (#38)

**Comment by cameronrutherford** [comment]
pre-commit documentation is a must

**Comment by cameronrutherford** [comment]
In addition to MR / Issue template, we should include requirements to manually run and have crusher CI pass before merging. Can't enforce through GitHub, so this is a manual / optional req

**Comment by cameronrutherford** [comment]
Captured reamining tasks in sub issues
